### ISSUE TITLE
Hearing echo on both iOS 7 and iOS 8 devices

### ISSUE THREAD

**Issue by fleetzen** [jefflinwood/twilio_client_phonegap#21]
Hi, we implemented the plugin in our phonegap app. We are able to successfully connect the two endpoints but hear a lot of echo on iphone. Android works just fine. Appreciate any insights

Thanks

**Comment by jefflinwood** [comment]
Hi,

Excellent - the PhoneGap plugin just wraps the iOS SDK from Twilio, so it shouldn't be introducing any echoing itself. The Twilio Client SDK does a pretty good job at managing echo itself, have you tried it out with the two phones in different rooms?

**Comment by peder541** [comment]
What version on the iOS SDK are you using?
