### ISSUE TITLE
I get "Class not found" in the status message.

### ISSUE THREAD

**Issue by onigetoc** [jefflinwood/twilio_client_phonegap#31]
I get "Class not found" in the status message.

Any idea why i get this message?

**Comment by jefflinwood** [comment]
Hi,

Can you see the Android logs on your project (adb logcat), or have it connected to Android Studio when you run it?

**Comment by onigetoc** [comment]
Hi, I tryed to create a Android Studio project but i can't run the simulator.
in the plugin.xml info it said. 
* Add the Twilio Client Java libraries (everything in the libs folder) to your project's libs folder - (platforms/android/libs)

is this refering to ?: https://github.com/twilio/twilio-java
Witch files i need, should i point the path in the plugin.xml ?
<source-file src=

I don't really get it when it comme to use command line or plugman and all these stuff.
I just download all i need and configure manually.

I just created a Github project with all the files to get help.
including all SDK, all needed file ect...
even two php file to get token and twiml.php to create twiml
https://github.com/onigetoc/test

**Comment by jefflinwood** [comment]
Hi,

I have an installation guide you can follow to get started here:

http://www.jefflinwood.com/2015/05/quick-installation-guide-for-twilio-plugin-for-phonegap/

Thanks!
Jeff Linwood

**Comment by onigetoc** [comment]
i will check it, 
If you can watch my project if you have time.
It would be great to have the full project on Github.
https://github.com/onigetoc/test

I have to said that this one is based on modification from this fork
https://github.com/jiju0nair/twilio_client_phonegap

**Comment by jefflinwood** [comment]
Hi,

That branch forked off my branch many commits ago, so I can't realistically support it.

Thanks!

**Comment by onigetoc** [comment]
Just the end of the tcPlugin.js has changed.
https://github.com/onigetoc/test/blob/master/www/tcPlugin.js#L141
