### ISSUE TITLE
Can't get Example App to work - new error with AudioSession

### ISSUE THREAD

**Issue by dstsay** [jefflinwood/twilio_client_phonegap#34]
Hi,

I've downloaded your example app and created a token server per Twilio tutorial instructions.  However, when I hit "dial", I get the following errors in the console:

2015-06-21 17:58:39.976 TwilioApp[535:62405] 17:58:39.976 ERROR:     [0x1055fc000] AVAudioSessionUtilities.h:111: GetProperty: AudioSessionGetProperty ('cilt') failed with error: '!siz'
2015-06-21 17:58:39.977 TwilioApp[535:62405] 17:58:39.976 ERROR:     [0x1055fc000] AVAudioSessionUtilities.h:124: GetProperty_DefaultToZero: AudioSessionGetProperty ('cilt') failed with error: '!siz'

Anyone experiencing this problem?

**Comment by dstsay** [comment]
I am using Twilio 1.2.3 and XCode 6.3.1

**Comment by jefflinwood** [comment]
Weird - is that from the Simulator or from a device? If so, on iOS 8?

Relevant StackOverflow thread for reference:
http://stackoverflow.com/questions/18935875/avspeechsynthesizer-error-audiosession

**Comment by dstsay** [comment]
Ah I figured it out. It wasn't working due to some problem with using
Twilios test credentials. Using upgraded credentials worked.  Oddly those
errors are still there but occur after the end of the call. It's some
problem with the Twilio Sdk itself

Thanks for a great plugin!

On Monday, June 22, 2015, Jeff Linwood <notifications@github.com> wrote:

> Weird - is that from the Simulator or from a device? If so, on iOS 8?
>
> Relevant StackOverflow thread for reference:
>
> http://stackoverflow.com/questions/18935875/avspeechsynthesizer-error-audiosession
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefflinwood/twilio_client_phonegap/issues/34#issuecomment-114124367>
> .
>


-- 
..............................................................
David Tsay, M.D., Ph.D.
Chief Innovation Fellow - NYP Innovation Center
Department of Cardiology
Columbia University Medical Center - New York Presbyterian Hospital

www.linkedin.com/in/davidtsay

P: (347) 229-1467
F: (815) 318-1930
..............................................................

**Comment by jefflinwood** [comment]
No problem! I hadn't seen that error before, and it was definitely coming from the Twilio SDK!
