### ISSUE TITLE
Crashing on incoming call

### ISSUE THREAD

**Issue by onigetoc** [jefflinwood/twilio_client_phonegap#35]
I successefully installed the Twilio client phonegap.
I can do call but It crash on incoming call in Android Studio and in the app on Android.

I checked the log, and when it crash i have no message.

Also, status message update on call and on end call but not on ready.

**Comment by onigetoc** [comment]
I'm using the latest Twilio Client Android library
https://www.twilio.com/docs/client/android

The status message are ok now but the app still crash on incoming call.

**Comment by ari3l** [comment]
I had the same issue the other day. The solution for was to put ALL of the files from the lib folder of the the Twilio SDK in the lib folder of your android project.

**Comment by jefflinwood** [comment]
Thanks @ari3l - I was unable to replicate this myself, and if you don't use all of the libraries, you'll definitely see a crash. I'll close this issue.
