### ISSUE TITLE
openssl crash

### ISSUE THREAD

**Issue by fedxgibson** [jefflinwood/twilio_client_phonegap#36]
I have been struggling with this for days. Using cordova 4.3.0.
After calling Twilio.Device.setup I get and exception in objective-c : EXC_BAD_ACCESS.

![screen shot 2015-06-23 at 4 23 20 pm]
(https://cloud.githubusercontent.com/assets/4645885/8316205/d69c085e-19cb-11e5-8277-d05352685c60.png)

As you can see the problem is when using openssl library. 
What would have causing this issue ?

**Comment by jefflinwood** [comment]
Hi,

Are you in the Simulator or on a Device? Also, which Twilio Client SDK version are you using?

**Comment by fedxgibson** [comment]
Hi! I am using an IPad and Twilio Client SDK is 1.2.3

**Comment by jefflinwood** [comment]
Ok thanks - the reason I asked is because Twilio had mentioned some OpenSSL things in their changelogs:

https://www.twilio.com/docs/client/ios/changelog

I wonder - are you using any other plugins that might have their own OpenSSL? Also is your iPad on iOS 8.3?

**Comment by fedxgibson** [comment]
iPad iOS version is 8.1 I am going to upgrade to 8.3 and see if there is any success!

**Comment by jefflinwood** [comment]
Ok! Are you using any other PhoneGap plugins?

**Comment by fedxgibson** [comment]
I am using OpenTokPlugin, PushNotification, CDVLocation and CDVDevice plugins for cordova. 
There was no success running the app on iOS 8.3..
Also I am using TwilioSDK from CocoaPods, do you think it may complicate things?
Other libraries I can see are:
libc++.dylib
libz.dylib
libsqlite3.dylib
libxml2.dylib

Do you think cordova version could have making troubles as well? May be downgrade?

**Comment by jefflinwood** [comment]
Hi,

If I had to guess it might be OpenTokPlugin - can you create a project that doesn't include it, and try again?

From the TokBox iOS  release notes, they are using OpenSSL in their framework - it might conflict with the version in the Twilio Client SDK.

https://tokbox.com/developer/sdks/ios/release-notes.html

**Comment by fedxgibson** [comment]
Hey, you were right! I remove references of openTok and finally could succeed.
Do you have any insight on how to get both plugins working together ?

**Comment by jefflinwood** [comment]
I don't have any good suggestions - both need OpenSSL, and presumably they must be different versions or otherwise incompatible. I'd suggest opening support tickets with both companies and asking them - there's no way to do this through PhoneGap, as far as I know.

**Comment by fedxgibson** [comment]
ok, thank you very much for your help! Very appreciate it

**Comment by jefflinwood** [comment]
Sure!
