### ISSUE TITLE
Publish this plugin on NPM

### ISSUE THREAD

**Issue by jefflinwood** [jefflinwood/twilio_client_phonegap#37]
Change plugin id to cordova-plugin-twilio-client

publish to npm

Map plugin id with pull request on https://github.com/stevengill/cordova-registry-mapper

**Comment by bsommardahl** [comment]
@jefflinwood Any movement on this? My team is trying to get this to work in a project in Phonegap Build so we need it in npm as soon as possible. If you can't get to this soon, would you mind if we do it?

**Comment by jefflinwood** [comment]
@bsommardahl Go ahead and do it! 

I haven't looked into this since flagging the issue.

**Comment by ikennah** [comment]
@bsommardahl where you able to publish this to npm? I would love to take advantage of it, I too am using phongegap build. Please let me know ASAP. Thanks.

**Comment by ikennah** [comment]
@jefflinwood, do you know if this was ever done?

**Comment by bsommardahl** [comment]
I think our team found a workaround so we didn't have to dev anything.
Sorry.

On Wed, Feb 3, 2016 at 2:50 PM ikennah <notifications@github.com> wrote:

> @bsommardahl <https://github.com/bsommardahl> where you able to publish
> this to npm? I would love to take advantage of it, I too am using phongegap
> build. Please let me know ASAP. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefflinwood/twilio_client_phonegap/issues/37#issuecomment-179458500>
> .
>
-- 
*Byron Sommardahl*
CTO, Co-Owner
Acklen Avenue | www.acklenavenue.com | 615-669-8239
632 Fogg Street Suite 8, Nashville, TN 37212

Acklen Avenue is a custom software development company committed
to creating quality software that people love to use.

**Comment by ikennah** [comment]
Are you able to share the workaround?

**Comment by bsommardahl** [comment]
I believe it involved manual builds on a dev machine. Not ideal but we
finished the project.
On Wed, Feb 3, 2016 at 8:02 PM ikennah <notifications@github.com> wrote:

> Are you able to share the workaround?
> On Feb 3, 2016 6:22 PM, "Byron Sommardahl" <notifications@github.com>
> wrote:
>
> > I think our team found a workaround so we didn't have to dev anything.
> > Sorry.
> >
> > On Wed, Feb 3, 2016 at 2:50 PM ikennah <notifications@github.com> wrote:
> >
> > > @bsommardahl <https://github.com/bsommardahl> where you able to
> publish
> > > this to npm? I would love to take advantage of it, I too am using
> > phongegap
> > > build. Please let me know ASAP. Thanks.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/jefflinwood/twilio_client_phonegap/issues/37#issuecomment-179458500
> > >
> > > .
> > >
> > --
> > *Byron Sommardahl*
> > CTO, Co-Owner
> > Acklen Avenue | www.acklenavenue.com | 615-669-8239
> > 632 Fogg Street Suite 8, Nashville, TN 37212
> >
> > Acklen Avenue is a custom software development company committed
> > to creating quality software that people love to use.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jefflinwood/twilio_client_phonegap/issues/37#issuecomment-179526370
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jefflinwood/twilio_client_phonegap/issues/37#issuecomment-179574559>
> .
>
-- 
*Byron Sommardahl*
CTO, Co-Owner
Acklen Avenue | www.acklenavenue.com | 615-669-8239
632 Fogg Street Suite 8, Nashville, TN 37212

Acklen Avenue is a custom software development company committed
to creating quality software that people love to use.

**Comment by ikennah** [comment]
@jefflinwood do you mind if I work on this, if so, it seems like the current plugin id/namespace is reserved.

**Comment by jefflinwood** [comment]
Hi,

Not at all, please do!

You'll need to change the cordova plugin id, I believe.

**Comment by jefflinwood** [comment]
cordova plugin add twilio-client-phonegap-plugin
