### ISSUE TITLE
Twilio.Device.ready(function(){}) not fired.

### ISSUE THREAD

**Issue by Muffasa** [jefflinwood/twilio_client_phonegap#42]
how can I tell when the Twilio Device is ready? 
I can make and ecive calls but this event never fires..any reason or a way to fix it?

**Comment by Inferner** [comment]
I am not sure but something is wrong in the java file. Offline is getting called when device is ready.

**Comment by tom367** [comment]
I can also confirm that this is happening with the newest version of the twilio sdk (1.2.5).

**Comment by jefflinwood** [comment]
This should be fixed with the latest version of the Android plugin
