### ISSUE TITLE
Twilio device status offline

### ISSUE THREAD

**Issue by fedxgibson** [jefflinwood/twilio_client_phonegap#44]
Hello!
I have been struggling with this since the beggining. I am developing an app with ionic + phonegap + twilio for ios and android. For iOS everything works perfect. Unfortunately it is not the case for Android.
The main issue is as the title says, for every token I try to setup twilio, I always receive status offline.

https://github.com/fedxgibson/toptierlabs-app

Here is an example app. 

require 'twilio-ruby'

account_sid = 'a'
auth_token = 'b'
appSid     = 'c'
capability = Twilio::Util::Capability.new account_sid, auth_token
capability.allow_client_outgoing(appSid);
capability.generate

And this is how I generate token. 
I would appreciate a lot your help. I know it is not precisely the plugin problem ( althought it could be, eventually ), but I dont know who else could help me.
Thanks in advance

**Comment by toptierlabs** [comment]
Same problem here.
Can anyone help?

**Comment by jefflinwood** [comment]
Hi,

It could be something in the latest Android Twilio Client SDK (1.2.6). I've tested the plugin through 1.2.2, but something could have broke the build. Let me see what I can do about re-running the tests.

**Comment by jefflinwood** [comment]
I can confirm that the Android Twilio Client SDK version 1.2.6 is not compatible with the plugin as it now stands. I'll open up a new issue.

**Comment by fedxgibson** [comment]
thanks Jeffinwood!
