### ISSUE TITLE
Android: Twilio Client SDK 1.2.6 - Device Ready not occurring with Plugin

### ISSUE THREAD

**Issue by jefflinwood** [jefflinwood/twilio_client_phonegap#45]

**Comment by jefflinwood** [comment]
The app is never receiving a callback for the device being ready.

**Comment by jefflinwood** [comment]
After taking more of a look at the problem - the real problem is that there is no "ready" event fired from the Twilio Device (on the Java side) on the Device Listener, and the new version of the SDK has introduced some more delay into the event.

The iOS Plugin gets around this by firing off a device status check one second after creating the device - this isn't really great, as it's a magic number. The Java plugin can do something similar for now, but should probably figure out a better way of managing this.

**Comment by fedxgibson** [comment]
Thanks Jeffinwood for taking a look, I was also checking and could not find a method in android sdk that listens for device status changes. 
So what do you suggest we can do ? Are you going to create a new commit with a quick fix ?

**Comment by jefflinwood** [comment]
I have a fix that delays for a second and then checks the status (similar to the iOS Plugin), so I'll do a little more testing and then update the plugin's Java source code.

**Comment by jefflinwood** [comment]
This is updated, and the plugin is now at version 1.0.3

**Comment by marcopadillo** [comment]
It seems this is happening again.

Cordova version: 6.0.0 (Android platform v5.1.1)
Android version: 6.0 (API 23)
Twilio Android SDK version: (latest as of today)
Twilio plugin version: 1.0.3
