### ISSUE TITLE
cordova IOS version 4.0.1 build error

### ISSUE THREAD

**Issue by greggreenhaw** [jefflinwood/twilio_client_phonegap#50]
My build is failing with the following error in the TCPlugin.m with cordova IOS 4.0.1 and the wkwebview engine enabled.

No visible @interface for CDVPluginResult declares the selector

**Comment by jefflinwood** [comment]
Hi,

I haven't had a chance to test it with the Cordova iOS 4.x plugins yet - does it work with the 3.9.x plugins and/or no wkwebview?

Thanks!

Jeff

**Comment by greggreenhaw** [comment]
I think they removed some deprecated code in IOS 4.0.1

**Comment by jefflinwood** [comment]
That's what it looks like - I'll investigate. Thanks for bringing it to my attention!
