### ISSUE TITLE
What is a good place to call device.connect() in iOS?

### ISSUE THREAD

**Issue by grgrtak** [jefflinwood/twilio_client_phonegap#53]
I tried to make an out-going call in `device.ready`, but it returns connection instead of device.
This is different from Twilio-js.
Can anyone help me with this?

**Comment by jefflinwood** [comment]
Hi,

You'd call:

connection = Twilio.Device.connect(params);

It should work in  Twilio.Device.ready(function (device) {})

**Comment by jilt1015** [comment]
@jefflinwood Thanks for your reply.
But the instance of connection is returned via `device` in the callback. I can't really understand it.

**Comment by jefflinwood** [comment]
Hi,

Take a look at the example app:

https://github.com/jefflinwood/TwilioClientPhoneGapExampleApp/tree/master/www/js

The plugin does work differently from Twilio's JS Client.

**Comment by jilt1015** [comment]
Thanks, I will take a look.
I forgot to mention that i am using the fork repo of yours. https://github.com/crossroads/twilio_client_phonegap
It may be an issue?

**Comment by jefflinwood** [comment]
So that one looks like they renamed Twilio.Device to TwilioClient.Device, so that could be a factor.

**Comment by jilt1015** [comment]
Yes, my code covers it already.
I just created a skeleton cordova project and applied your example project.
It apparently returns connection through the `device` variable here.
`Twilio.Device.ready(function (device) {
   console.log (device); //      this returns connection
    $('#statusMessage').text('Ready to start call');
});`
