### ISSUE TITLE
is it support video calls?

### ISSUE THREAD

**Issue by sumanranjanpanda** [jefflinwood/twilio_client_phonegap#54]
I want to integrate video call functionality from mobile device. 
Like [https://www.twilio.com/docs/api/video/guide/quickstart-android](https://www.twilio.com/docs/api/video/guide/quickstart-android)

When I tried to use `Twilio.AccessManager` or  `Twilio.Conversations.Client` helper methods, that didn't work.

Is this plugin supports the video call functionality? Could you please help me on this?

Thanks,
Suman

**Comment by jefflinwood** [comment]
Hi,

Great question - the current version of the plug in does not support video yet. That will need to be added to the plugin.
