### ISSUE TITLE
Can't hear the sound transmission on Android 6

### ISSUE THREAD

**Issue by dunice-potapov** [jefflinwood/twilio_client_phonegap#55]
I tested it on two devices with Android version 6.
Also, same code works for Android 5 and Android 4.

My use case:
1. Someone calls the phone number that assigned with Twilio
2. URL on Twilio provides the TwiML that opens the conference with unique room name
3. The server code with TwiML URL initiates the outgoing call to Ionic app
4. Ionic app on Android handles the incoming call from conference
5. User of Ionic app answer the call

**Comment by dunice-potapov** [comment]
Also, same code works for Android 5 and Android 4.

My use case:
1. Someone calls phone number that assigned with Twilio
2. URL on Twilio provides the TwiML that opens the conference with room name of user that initiated the call
3. Ionic app on Android handles the incoming call from conference
4. User of Ionic app answered the call

**Comment by jefflinwood** [comment]
Hi,

Thank you for the detailed feedback about this - which version of the Twilio Android SDK are you using, and which version of the PhoneGap Android plugin?

Thanks!

**Comment by dunice-potapov** [comment]
Hi, @jefflinwood 

I'm using the last versions of plugins from official sites:
- Twilio Client Android SDK - 1.2.9 (Feb. 19, 2015)
- PhoneGap Android plugin - can't find it in my project, may be not installed. I'm not sure.

All plugins that I'm using are http://screencast.com/t/4TKW6HBGqm

twilio_client_phonegap I install only for Android via plugman.

Thanks

**Comment by dunice-potapov** [comment]
Hi Jeff,

Do you have the same problem? Can you check it?
What can I check for detailed description else?

Thanks,
Alexander

**Comment by dunice-potapov** [comment]
Also I used the Android Target SDK 22 - the same issue.
