### ISSUE TITLE
ReferenceError: Cordova is not defined

### ISSUE THREAD

**Issue by deepugn** [jefflinwood/twilio_client_phonegap#59]
Hi,

When i call Twilio.Device.setup(), i am getting a reference error when i test from ios emulator and browser.
`ReferenceError: Cordova is not defined`
I have included cordova.js in my index file. This may not be an issue, may be an error from my side, asking here since i don't have another option.

Let me tell the scenario, i am trying to make a softphone type of application for ios and android, using ionic framework and twilio, without a server component if possible.

Best Regards,
Deepu.

**Comment by jefflinwood** [comment]
Hi,

Have you tried the example app out with your set up?

https://github.com/jefflinwood/TwilioClientPhoneGapExampleApp

You will need a server component to provide capability tokens for your app - take a look at the Twilio Client documentation.

Thanks!

**Comment by deepugn** [comment]
Hi,
Thank you very much for replying. The same  is  happening
Initially this error comes up
```
0     396757   log      exeption nativeEvalAndFetch : ReferenceError: Can't find variable: cordova
1     400325   error    ReferenceError: Can't find variable: Twilio, http://localhost:8100/js/phoneApp.js, 
```

when i copy tcPlugin.js manually to js folder near phoneApp.js this error comes up
JS changed:   www/js/tcPlugin.js
`0     560331   error    Uncaught ReferenceError: Cordova is not defined, http://localhost:8100/js/tcPlugin.js, Line: 26`


Best Regards,
Deepu

**Comment by deepugn** [comment]
Hi,

Thanks for the quick response, it now works, I've set up a server component for the capability token,  but now the issue is that call is not getting past  Cordova.exec() and call the native to execute the code.

I was trying to dial a number it reaches till the Cordova.exec(), but nothing happens after that, neither the call is connecting or any error logs coming up.

Best Regards,
Deepu.

**Comment by marcopadillo** [comment]
Hi @deepugn, what version of Twilio's Android SDK did you use?
