### ISSUE TITLE
Trouble installing plugin

### ISSUE THREAD

**Issue by sambengtson** [jefflinwood/twilio_client_phonegap#73]
Hello,

I'm getting the following error while installing this plugin.  Anything that I should be looking at here specifically?

> sam@sam-VirtualBox:~/Documents/Ionic/tkc-telecom-mobile$ cordova plugin add  https://github.com/jefflinwood/twilio_client_phonegap.git
> Error: Failed to fetch plugin https://github.com/jefflinwood/twilio_client_phonegap.git via registry.
> Probably this is either a connection problem, or plugin spec is incorrect.
> Check your connection and plugin name/version/URL.
> Error: npm: Command failed with exit code 235 Error output:
> npm ERR! addLocal Could not install /tmp/npm-4326-5795acd9/git-cache-872ddb90/596f84661051f86c1f37d258f3e689f045f886a0
> npm ERR! Linux 4.4.0-78-generic
> npm ERR! argv "/home/sam/.nvm/versions/node/v7.4.0/bin/node" "/home/sam/.nvm/versions/node/v7.4.0/bin/npm" "install" "https://github.com/jefflinwood/twilio_client_phonegap.git" "--save"
> npm ERR! node v7.4.0
> npm ERR! npm  v4.0.5
> npm ERR! code EISDIR
> npm ERR! errno -21
> npm ERR! syscall read
> 
> npm ERR! eisdir EISDIR: illegal operation on a directory, read
> npm ERR! eisdir This is most likely not a problem with npm itself
> npm ERR! eisdir and is related to npm not being able to find a package.json in
> npm ERR! eisdir a package you are trying to install.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/sam/Documents/Ionic/tkc-telecom-mobile/node_modules/npm-debug.log

**Comment by sambengtson** [comment]
Seems to work installing using plugman :+1:

**Comment by jefflinwood** [comment]
Hi,

I think the problem is that it needs to be published to npm - let me look into that.
