### ISSUE TITLE
Unable to use Plugin.

### ISSUE THREAD

**Issue by jonathanhollander** [jefflinwood/twilio_client_phonegap#76]
Hello, I'm trying to use the Twilio PhoneGap/Cordova Client Plugin,

I've got a fresh copy of Node, Cordova, and created a new project.

I've installed the plugin via: cordova plugin add twilio-client-phonegap-plugin

But when I go use the plugin, the "Twilio" variable on the window is undefined.

I noticed that the github links to an example app that hasn't been updated in 2 years (https://github.com/jefflinwood/TwilioClientPhoneGapExampleApp) should people still follow these directions?

Besides this, for all other plugins I am using, there usually exists a folder for plugin inside of the "platforms/ios/www/plugins/" folder. For example I am using the "cordova-plugin-appversion" plugin, so inside this folder I see a "cordova-plugin-appversion" folder with the plugins js source.

I see nothing like that for the twilio client phonegap plugin, there is no folder related to twilio in the "platforms/ios/www/plugins" folder.

**Comment by jonathanhollander** [comment]
In case anyone else runs into this,  I figured it out. I needed to include a normal <script> tag and reference the source code. All other plugins I've used have included the source into the various platform and i've never had to add it into the html directly

**Comment by jefflinwood** [comment]
Hi,

Thanks - this plugin is pretty old by Phonegap standards, and probably doesn't follow the best practices. The example application should still work ok. I'll look at bundling the plugin source into the platform/www directory - that would be nice!
