### ISSUE TITLE
Wrong argument in disconnect handler for Connection

### ISSUE THREAD

**Issue by cameronhatfield** [jefflinwood/twilio_client_phonegap#82]
```
TwilioPlugin.Connection.prototype.disconnect = function(fn) {
        if (typeof(argument) == 'function') {
            delegate['onconnectiondisconnect'] = argument;
        } else {
            Cordova.exec(null,null,"TCPlugin","disconnectConnection",[]);
        }
}
```
fn should be argument / or argument should be fn.

**Comment by jefflinwood** [comment]
Hi,

Let me take a look at that, but I'm pretty sure you are correct from reading that code. Thanks!

**Comment by tonysumi** [comment]
Hi,
Regarding call Disconnect, which function get triggered when receiver disconnects the call?
I've been trying to use the below one but It's not always called. Please guide me.
window.Twilio.Device.disconnect(function (connection) {
});
Thanks

**Comment by jefflinwood** [comment]
Hi, fixed in https://github.com/jefflinwood/twilio_client_phonegap/pull/83
