### ISSUE TITLE
When we use this plugin do we really need to separately add ios and android twilio libs?

### ISSUE THREAD

**Issue by shivanibhanwal** [jefflinwood/twilio_client_phonegap#89]
@jefflinwood  I am little confused with the advantage of this plugin. We have used in our project a few years back and I see we are using this plugin, then we are added twilioClient.js separately in out Vendor folder and not just then. We also add on more LIB folder which contains the Ios and android libs e.g.
TCConnection.h, TCConnectionDelegate.h, TCDevice.h, TCDeviceDelegate.h, TCPresenceEvent.h, TwilioClient.h, libTwilioClient.a, libcrypto.a ,	libssl.a

So we really need to have all this? I am really unable to understand the purpose. 
For background, we have an Ember.js app web/mobile. we use Cordova for mobile with ember-cli-Cordova.

I will really appreciate your quick response on this that will help me decide the right way.

Thanks 
Shivani

**Comment by jefflinwood** [comment]
The reason this plugin uses all of these libs is that the Twilio Client JS does not work inside a web view in a mobile app - this could change in the future (and ideally this plugin would go away).

**Comment by shivanibhanwal** [comment]
Thanks @jefflinwood 👍 got it.
